Fixes DirectInput Joystick Lag Issue
liballeg/allegro5 pull request #1173
Opened 2020-09-20 20:40 UTC by NewCreature

As discussed in issue #1026, this fixes the joystick lag issue caused by frequently calling `IDirectInput8_EnumDevices()`. Instead, we register to receive notifications when devices are connected/disconnected. If we are notified of a device change, we notify the joystick thread to re-enumerate the devices.

2020-09-20 21:06 UTC, beoran approved these changes

2020-09-20 21:08 UTC, beoran commented
LGTM. I assume you tested this well with several different joysticks. 

One extra thing we could do is see if the connected device is an XInput one, in which case no rescan is needed.

2020-09-27 04:19 UTC, SiegeLord requested changes
Looks great, and appears to work for me. Just one potential race condition I think might be a problem.

2020-09-27 04:19 UTC, SiegeLord commented on src/win/wjoydxnu.cpp
> +  need_device_enumeration = true;
Shouldn't this be guarded by joydx_thread_cs?

2020-10-13 09:17 UTC, SiegeLord commented
Merged as https://github.com/liballeg/allegro5/commit/07a7ce7a70b322657259447d6ca0d11205a0efed. Thanks!

2020-10-13 09:17 UTC, closed without merging